### ISSUE TITLE
Run cae.sh in another working directory

### ISSUE THREAD

**Issue by carlomontec** [imirzov/ccx_cae#2]
Hi Igor,

thank you for your AMAZING pre/postprocessor. Is it possible to run cae.sh from another working folder? Or should I rund it always from the ccx_cae folder?

**Comment by imirzov** [comment]
Hi, Carlo!
You shouldn't change directory to 'ccx_cae'. In this case just use full path to cae.sh in the Terminal.
But do not move cae.sh - it has rigid link to 'ccx_cae/src/cae' file.
If you need a shortcut to 'ccx_cae/src/cae' file - google about .desktop files in Linux.
